### ISSUE TITLE
Typora not recommended as markdown editor anymore (not free to use anymore)

### ISSUE THREAD

**Issue by elias-plank** [litec-lectures/litec-workspace#1]
# Fix README
 README contains information that Typora shall be used as a markdown editor, I suggest to change it to MarkText or other free alternatives. VSCode could also be mentioned as it supports markdown via extensions.

---
![not-willing-to-pay](https://miro.medium.com/max/1400/1*HYIwGvO51orRoDCvSFquzg.jpeg)

**Comment by litec-hasp** [comment]
DONE! Changed to MarkText...
